### ISSUE TITLE
Add integration flow fails

### ISSUE THREAD

**Issue by watercrossing** [jfparis/homeassistant_nationalrail#1]
Hi. I have just tried to install this custom component, and I am getting the following error (running home assistant core 2023.6.2 on python 3.11):

```
2023-06-19 17:12:40.473 ERROR (MainThread) [custom_components.nationalrailuk.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/nationalrailuk/config_flow.py", line 87, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/nationalrailuk/config_flow.py", line 43, in validate_input
    res = await my_api.async_get_data()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/nationalrailuk/client.py", line 194, in async_get_data
    raw_data = await self.get_raw_departures()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/nationalrailuk/client.py", line 86, in get_raw_departures
    batch = await self.client.service.GetDepBoardWithDetails(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/zeep/proxy.py", line 64, in __call__
    return await self._proxy._binding.send_async(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/zeep/wsdl/bindings/soap.py", line 156, in send_async
    response = await client.transport.post_xml(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/zeep/transports.py", line 235, in post_xml
    response = await self.post(address, message, headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/zeep/transports.py", line 220, in post
    response = await self.client.post(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1848, in post
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 261, in handle_async_request
    return Response(
            ^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 245, in handle_async_request
    # up as HTTP/1.1.
               ^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/httpcore/_async/connection.py", line 92, in handle_async_request
    async def _connect(self, request: Request) -> AsyncNetworkStream:
                    ^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/httpcore/_async/connection.py", line 69, in handle_async_request
    )
      
  File "/srv/homeassistant/lib/python3.11/site-packages/httpcore/_async/connection.py", line 117, in _connect
    }
      
  File "/srv/homeassistant/lib/python3.11/site-packages/httpcore/backends/auto.py", line 31, in connect_tcp
    )
      
TypeError: AsyncIOBackend.connect_tcp() got an unexpected keyword argument 'socket_options'
```

This looks almost like an issue with zeep (I have version 4.2.1 installed) and its use of HA's AsyncIOBackend to me, but I thought I raise this here rather than heading straight to zeep.

**Comment by watercrossing** [comment]
And this pin is already fixed in homeassistant master (https://github.com/home-assistant/core/blob/5303bef83eaa23c65299b2c24d9390f85fb48365/homeassistant/package_constraints.txt#L105), so it will be fixed soon.
