### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by chrisgwynne** [jfparis/homeassistant_nationalrail#10]
`Unexpected exception

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/zeep/transports.py", line 213, in _load_remote_data
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Redirect response '301 Moved Permanently' for url 'http://lite.realtime.nationalrail.co.uk/OpenLDBWS/wsdl.aspx?ver=2021-11-01'
Redirect location: 'https://lite.realtime.nationalrail.co.uk:443/OpenLDBWS/wsdl.aspx?ver=2021-11-01'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/nationalrailuk/config_flow.py", line 90, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nationalrailuk/config_flow.py", line 42, in validate_input
    my_api = NationalRailClient(data[CONF_TOKEN], "WAT", ["CHK"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nationalrailuk/client.py", line 61, in __init__
    self.client = AsyncClient(wsdl=WSDL, settings=settings, plugins=[history])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zeep/client.py", line 76, in __init__
    self.wsdl = Document(wsdl, self.transport, settings=self.settings)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zeep/wsdl/wsdl.py", line 92, in __init__
    self.load(location)
  File "/usr/local/lib/python3.12/site-packages/zeep/wsdl/wsdl.py", line 95, in load
    document = self._get_xml_document(location)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zeep/wsdl/wsdl.py", line 155, in _get_xml_document
    return load_external(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zeep/loader.py", line 89, in load_external
    content = transport.load(url)
              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zeep/transports.py", line 123, in load
    content = self._load_remote_data(url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zeep/transports.py", line 215, in _load_remote_data
    raise TransportError(status_code=response.status_code)
zeep.exceptions.TransportError`

I get this error when trying to add stations.

**Comment by jfparis** [comment]
Look like some weird redirect server side. Not experiencing that one now
