### ISSUE TITLE
Integration won't load (after update to 24.12?) 

### ISSUE THREAD

**Issue by skinnypope** [jfparis/homeassistant_nationalrail#15]
Not sure if it was related to me updating to 24.12 but this integration now fails - logs:

Logger: homeassistant.setup
Source: setup.py:334
First occurred: 09:16:37 (1 occurrences)
Last logged: 09:16:37

Setup failed for custom integration 'nationalrailuk': Unable to import component: No module named 'cgi'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/nationalrailuk/__init__.py", line 8, in <module>
    from .client import NationalRailClient
  File "/config/custom_components/nationalrailuk/client.py", line 5, in <module>
    from zeep import AsyncClient, Settings, xsd
  File "/usr/local/lib/python3.13/site-packages/zeep/__init__.py", line 1, in <module>
    from zeep.client import AsyncClient, CachingClient, Client
  File "/usr/local/lib/python3.13/site-packages/zeep/client.py", line 6, in <module>
    from zeep.transports import AsyncTransport, Transport
  File "/usr/local/lib/python3.13/site-packages/zeep/transports.py", line 11, in <module>
    from zeep.utils import get_media_type, get_version
  File "/usr/local/lib/python3.13/site-packages/zeep/utils.py", line 1, in <module>
    import cgi
ModuleNotFoundError: No module named 'cgi'

**Comment by VectorConnor** [comment]
Same issue for me

**Comment by jfparis** [comment]
Please update to latest version

**Comment by skinnypope** [comment]
Fixed thank you
